baseURL: https://sall-lab.gitlab.io/my-site/
languageCode: en-us
title: "Toha"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
#googleAnalytics: UA-xxxxxxxx

# Enable Disqus forum
#disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Github Repo URL. This is used to add "Improve This Page" button
  gitRepo: https://sall-lab.gitlab.io/my-site
