name: github pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      #- name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        #run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: ss-o/ss-o.github.io
          publish_dir: ./public
          keep_files: true
          user_name: ss-o
          user_email: sall@w-ss.io
          publish_branch: master
        #   cname: ss-o.github.io
